# `r tint` {#int}

#### Abstract {-}

(ref:abs-int)

#### Keywords {-}

(ref:key-int)

***

The question of what to read is simple to be sure, but in fields of scholarly consumption and production it is nonetheless fundamental. Scholarship is a creative profession where a stock of cultural knowledge forms a greater part of the infrastructure of production than in other fields. This is not to say that other occupations, especially manual ones, lack creativity. It is to say that in such fields knowledge has a limited infrastructure. Whereas the know-how of the brick layer is black boxed in her tools and technology and in the human capital she develops by experience and tacit social learning, for the scholar as bricoleur there exists in addition the distinctively overdeveloped feature of cultural archiving as a universal memory. Except perhaps in outstanding feats of primary research, contributions to scholarship are legitimate to the extent that they have used the archive correctly. This problem of using the archive, by which I mean all libraries and other organizations that help scholars find published work, is easily expressed by the question, "what to read?" Paradoxically, the over-development of the archive induces a functional imperative: to the extent that more and more of scholarship is memorable, mechanisms must develop to forget large swaths of intellectual history. A person who studied a random draw from the archive, even a monumental one, would no doubt qualify as an educated person. Professionally, however, they would have answered the question in a tragically wrong way. From the perspective of other scholars, there are right and wrong choices about what to read. Because it is so easy to access scholarly memory, the operative question really becomes "what not to read?"

Most occupations are not saddled with a heavy burden of memory, remembering in the fashion of a Markov chain only the most recent chapter in their history. Rather than in archives, memory is codified in tools and technology. Though Internet search and self-publishing services, especially video and image based ones, are creating archive-like infrastructure for even manual occupations, the functions are different. Contemporary Internet repositories provide knowledge as factors of production to anyone who queries them, but many do not purport to be archives in the sense that a historical record of cultural products is preserved for posterity. They are much more concerned with access to contemporaneous than to historical material, and indeed the particular configuration of the contemporary that sells the most advertisements ahead of search results. True historical archives of the Internet, such as the Internet Archive or Common Crawl, are not used by the public. Indeed why would they be; they expose the dizzying complexity of the history of the Internet, which, even in only its contemporaneous facet is already overwhelming. The Internet searcher tends to be satisficing, and the search companies have refined their ranking of results to meet their users' search budgets efficiently.

Searching and finding are different procedures; to search is to turn over every rock, whereas to find is to turn over only the correct rock. The searcher encounters many tricks before alighting on a treat, and must make an effort to reject the false positives. The finder exploits indexing technology that allows her to bypass the wrong material altogether. Without a normative compulsion to make history accessible, Internet search engines, which are actually find engines, avoid the scholarly paradox of memory, which is that in the university system great pains are made to remember everything just so that the correct material may be forgotten. Scholars do not yet have find engines that protect them from encountering irrelevant material, and it is a professional competency to be able to quickly separate wheat from chaff.

## Status exclusion

Though cultural abundance may be cultivated on the universal egalitarian grounds that knowledge be made accessible to all, the complexity of the archive creates an opportunity for the establishment of social hierarchy. Because the archive's size so wildly outstrips individual and organizational capacities to know its contents, methods of selection become paramount. Indeed the power to control what counts as a legitimate selection becomes a basis for authority and the conferral of status. Status reflects a person's generalized ability or inability to accrue resources to herself over the claims of others. Social institutions define the conditions of status attainment, and different institutions validate statuses according to different norms, truths, and values. Knowledge as a valued resource mediates social relationships and stabilizes status hierarchies differently in professions than in education. The stability of status hierarchies depends on a qualified segregation of these institutions, as the norms of one can be corrosive to the norms of the other.
<!--password credential or shibboleth; not a shibboleth because it can be mastered-->
In the cynical view of professions, scholarship is the encryption of memory by secret sets. If each field of professional scholarship is a club, their passwords are particular lists of items from the archive. Comers arriving with off list items or without enough of the correct items may be held at the door, or if they are given entry, will be marked with a scarlet letter. To say that the password items are the only ones relevant to knowledge in the field is incredible; the depth of the archive always impresses even the most experienced divers. The importance of the list is not only in its knowledge potential but also in its exclusionary function. Knowledge of the list is a qualification, ignorance a disqualification for club membership.

Why check qualifications at all? The archive, in rendering knowledge accessible and transparent, obviates a conventional function of professions which is to restrict their ranks by controlling access to secret knowledge. If the knowledge is not secret, a field must find other mechanisms of exclusion to establish itself as a profession. To make matters worse, the university contexts in which scholars work tend to confront them with a public and to impose on them a duty of education or service. Professionals who are embedded in markets trade the products of their capacities, goods and services, for money. Their clients have no serious interest in acquiring the professional's capacity to produce, and this inscrutable cognitive base [@DiMaggio1983Iron\:152] constitutes the client's experience of the professional's expertise.

Scholarship is based in the university and not in the market, and here the value orientation to knowledge is very different. Professionals default to entering into client, rather than peer, relationships.  The scholar's "clients"--students, the public, and other scholars--may be as interested in the production as they are in the product. From an intellectual property perspective, "ideas are strongly nonrival (they are not used up) and only weakly excludable (they are difficult to protect from use by others)" [@Thompson1995Conceptions\:278]. Because educational commitments promote the free flow of ideas, knowledge qua knowledge cannot be the basis of professional exclusion within an institution designed to diffuse it.

Knowledge qua password is arbitrary with respect to content in that club knowledge is not of better quality than other resources made accessible by the archive. Whereas in unarchived fields knowing is enough to gain club membership, archived fields require a substitute exclusion mechanism to safeguard hierarchy. This explains the prominence of priority in the attribution of discovery over the mere fact of possessing knowledge, yet priority defines hierarchy internal to professions and would be overkill in defining the external relations of the profession. Simply, members of a scholarly field need not have invented knowledge to use it to assert their membership status against nonmembers. But the question of knowledge quality, why club knowledge is not substitutable for other available knowledge, is a constant erosive force against the club's foundation. For the more status insecure in the profession, pride in ignorance of foreign content becomes a weak value to paper over the contradiction, whereas the status secure, who have enjoyed better employment contracts and more time to explore the archive, understand that forbidden fruit are in fact interesting and no real threat to them.

This constant need to build redoubts against deteriorating club walls exists only because scholarship has, in the United States at least, been embedded in educational networks whose value orientation to knowledge opposes that of professions. One modification of professional esotericism is that the passwords are a group secret, which means that anyone who knows they exist can find them out, master them, and gain club membership (if not club rewards). This satisfies the openness required by universalist educational values. To satisfy the closure required by the professions, password mastery must have nontrivial costs. In making the password mandatory clubs construct excludability in an arbitrary set of ideas whose components are not naturally excludable. This encryption cost, like the blockchain, makes the detection of fakes easy while creating trust between incumbents and the newcomers who pledge to honor the prior commitments of the field.

This password structure faces destabilizing threats. The entropic force of the archive has already been mentioned, which by itself stresses scholarly boundaries because anyone can acquire expertise independently of professions and then use that to make claims on club goods. Clubs are able to deflect these claims only when the the symbolic value of the password is not deflated. The other destabilizer is educational values, which mandate that rewards accrue to mastery of process (learning) rather than mastery of products (knowing). Educational values are equitable and universalistic and therefore delegitimize all nonrandom exclusion mechanisms like the password system. But when compromised by professional values education merely requires scholars to reduce the costs of password mastery by forcing investments in pedagogy. If they were ever able to dominate professions education would force open club boundaries and destroy field cohesion. Defenders of professions would label this a situation of hackery, while detractors would contend that it would still be productive to resource people with idiosyncratic knowledge bases, i.e. those who eschewed the password system. When education and profession are in balance, the password system integrates the conflict between them, forcing some egalitarian openness to replenish the ranks of professions.

This functioning of the password system in not how it is experienced by people. Phenomenologically knowledge sets are not viewed as arbitrary but are rather shrouded in a reputational aura. This aura is manifest as a taste for scholarship. To be professional is to trade in status, to know what are the tasteful combinations of resources. To be a successful professional is to never have wasted time tasting forbidden fruit. It is the laity who bear the brunt of the exclusion mechanism, while clergy who have long ago armed the traps spectate. A lay seeker approaches the academic archive and at great cost of attention plumbs its depths for enlightenment. The archive's complexity dooms her to check out a curriculum so hopelessly tacky that it will only certify her lay status. In her humiliation she feels a deep injustice that her knowledge is not recognized. A different seeker with guile enough to learn the password first plumbs only the relevant parts of the archive, and upon mastery enters the social compact with incumbent professionals. The two seekers stand next to each other but on either side of a gate. That they are equally educated is clear, but their paths at this point will diverge, one toward the interior of a profession and the other into the wilderness.

In this fable the archivists themselves are tragic figures, stretched as they are between people who profess (declare publicly) and people who educate (lead out). Librarians much prefer to help laity who in their tastelessness welcome guides who will lead them through the grandeur of the archive. The archivists gifted scholars with access to an immortal memory, and looking the horse in the mouth scholars made rules to protect themselves from the responsibilities of using most of it. Paradoxically, in taking the burden of memory off of the shoulders of scholars, thereby freeing them of the pain of legacy suffered by other artists [@Lang1988Recognition], librarians created a maze of knowledge in which clergy could trap laity.

## Generic isomorphism

How does an established scholar know what are the lucrative curricula that can be developed from the archive? Notwithstanding its knowledge-agnostic role in reifying social hierarchy, the password list is one answer to the question of what to read, and the rules for putting the list together are not entirely arbitrary. There are tacit conventions that both legitimate the password list within the profession and make it possible to recognize whether newly encountered work is relevant to the field. The password list answers the question of what to read only in a very narrow sense that guards the exterior of a scholarly field, the relationship between clergy and laity. Given password mastery, how then do professional scholars know what (not) to read as they extend the field while avoiding an internal erosion bubbling up from their own scholarly creativity? How do dislocated scholars coordinate their activity so as to produce self-similar work in the interests of the profession? There are several formal and informal structures that facilitate and compel scholars to make the same choices about what to read.

An obvious one is the supposed normative isomorphism of graduate program syllabi, which act like maps to navigate the maze of the archive. These syllabi may or may not also teach the password of a field, a fact that may be difficult for students to discern. Universities tend to grant great autonomy to professors in writing syllabi, who in the course of their professional travails may not be given opportunities to read what they want. In being forced to carve out time with subordinates, faculty are caught between personal indulgence and a more or less strongly felt fiduciary responsibility to set students on the correct path. Students, having at most a weak basis for discerning whether a syllabus serves their interests or not, would have little recourse but to trust faculty even if that were not already built into the role relationship. If we have less than perfect faith in the strength of educational ethics among faculty, then we should expect that among graduate syllabi are many lists of what not to read. Students who trust too much in the formal curriculum may be lead astray, and even without trust, they may still be left ignorant of where to invest their labor.

In each graduate program there then must be a hidden curriculum, a map of the archive of higher quality than the formal syllabi. The argument of this study addresses the question of where such a curriculum comes from. The provisional answer is that in the informal spaces of graduate programs knowledge of scholarly genre is learned from extracurricular engagement with professional conferences. It is in conference programs that the tacit rules of academic genre are learnable. These genres form the first parsing of the archive for neophytes. Indeed at the most generic level graduate students, if they are confident enough to locate themselves quickly, develop a taste for what not to read. Genre as the foundation for a taste for scholarship serves to restrict a student's wandering to a delineable sector of the maze. If they can develop this proto-taste early enough in their careers, they will be armed with the stereotypes necessary to stop reading the wrong and start reading the right material. While this is not enough certainly to make clergy of laity, it is the first step.

Genre is the tacit essence of the password list, the interpretive code that is the taste for scholarship. Genre rules may be difficult to describe explicitly, and it is easier to argue about whether particular cultural items (ever available in the archive) are genre conforming or not. Genres bear labels that are too easy to reference, and when it comes time to describe their content it is those particular items whose classification status is unassailable that will serve to represent genre content, paradigms in the pre-Kuhnian sense of a primitive standard against which others may be compared.

The indulgences of syllabi are pejorative only in the sense that they represents genre nonconformity. Indeed scholarly indulgence may be educationally beneficial to students even while it is, as an opportunity cost, professionally wasteful. The opposite of generic here is not specific but rather idiosyncratic; a species has a known genre classification, whereas idiosyncrasy is unclassifiable, or at least unclassified. Indulgent idiosyncrasy, for instance the reading of a great book of a bygone era, may be very interesting especially when genre conforming content is boring precisely because it is generic. Yet for all its charm idiosyncrasy, if it cannot be accurately classified by professionals, does not advance professional interests. Students who wish to be educated may enjoy it, but those who wish to be professionalized ought to avoid it. So there is indeed a correct way to approach the archive, correct in the sense that certain draws establish eligibility to access scholarly professions. The reward relevant to neophytes is access to the first job, which if it can be secured grants access to facilities and some scope for indulgences.

This is not to say that students must directly encounter conference programs to learn genres. Genres may be communicated as stereotypes within local departmental codes and discourses. Such local cultures may either proudly or unwittingly contradict national genre standards, yet they will face perennial alignment challenges when departments interview candidates for jobs. Candidates have tailored themselves for a national market and will likely resemble the national genre code (that of our professional conference). Even if a candidate prepares a version of herself to convey the right "fit" in a particular locale, her actual scholarship will likely have been prepared for the generic rather than the specific audience. Thus while it may seem that the job holder would take priority over the job seeker, both contest and contestant have conditioned their expectations to maximize their appeal to as broad a field as possible.

The maximization strategy is simple: conform to the national genre system. The power of genre is this regulation of expectations across the supply and demand sides of the market. If either the local departmental culture or the candidate abrogates the national genre system with an indulgent idiosyncrasy, an exchange that would have been mere performance will devolve into a status challenge. The ornery party will have deflated the discursive potential that genres enable and will have raised the hackles of its interlocutors by requiring additional effort to recognize the unlabeled work before them. This cognitive tax created by the defiance of genre will need to be paid with a loan taken using one's reputation as collateral.

The abrogation gambit is as risky for the contest as for the contestant, but to call it a gambit assumes a high level of sophistication. At one level genres are the most accessible form of knowledge in a cultural field. Everyone may know that classical is a genre of music without knowing much of anything about classical music. Knowing the label is the primitive form of genre knowledge; knowing how to categorize a particular unlabeled cultural object the next most primitive, and so on through gradations of knowledge that at the most advanced level reflect a performer's ability to strategically mobilize genre conventions to control an audience's experience.

Nonetheless, the reputation sanction for genre abrogation will be assessed regardless of whether the performer colors wittingly or unwittingly outside of the lines.

Several fields of scholarship apply the term genre to describe or explain variations in content in other fields of cultural production, most commonly in literature and music. Though genres are commonly accepted to be classification systems in particular cultural domains, their ontology and hence validity tends to be assumed rather than demonstrated. Given fields of cultural production and consumption (or poiesis and esthesis depending on one's discipline) that are prolific and innovative, one would expect genres to be soluble. In fact they are highly durable. The disciplinary structure of higher education offers an example of one of the more durable cultural classification systems. 

## Influence

@Parsons1963Concept used the term influence to describe generalized knowledge-based authority. Influence is a symbolic medium of communication like money, which represents a value without being the value. Symbols are more easily transacted than the real resources they represent, and they allow trades to be constructed as social commitments before real resources are mobilized. The password list is a symbol of a supplicant's capacity to uphold genre conventions and safeguard the status of a field, a promise which they aim to transact for access to real resources, namely employment, in a scholarly profession. Like money, influence is subject to inflation (requiring a candidate to know even more than the password list) and deflation (being unimpressed no matter how much a candidate knows). Importantly influence is not reputation; it is a feature of the status of the field rather than the status of an individual. All knowledge holders transacting with a club will be similarly affected by inflation or deflation of the field's influence.

There are many more varietes of influence operative in scholarship beside the password system. One of the features of symbolic media is the displacement in time between acquisition and possession. A coffee paid for is socially acquired while one waits for a barista to finish pouring it. In scholarship knowledge tends to be what is transacted, and as with consumer goods, knowledge can be socially acquired prior to its posession. The reputed meaning of texts is an example of acquisition (understanding) without possession (reading). Though above I went to great lengths to argue that the archive is an amazing institutional memory, library technology may paradoxically make it easy to forget scholarship [@Cevolini2016Forgetting]. A scholar who is confident that knowledge is safely protected in archives and who believes that it can always be accurately retrieved is relieved of the urgency of digesting it now. Punting on understanding *from* texts opens space for exogenous understandings *of* texts. Contemporaneous cultures and societies constraining the reader prejudge the meanings of texts.

While scholars genuflect to a quest for truth, the practical incentive to minimize time spent reading leads to several methods of collusion in the reduction of texts. As has been discussed, any text that can be commonly declared irrelevant need not be bothered with it all. Second, a text need not be read to be understood, as their meanings may have a common sense. Texts have reputations and reputed meanings. These reputations like those of people stand in for the real thing in scholarly discourse. These mediated versions of the truth act as promissory notes in scholarly transactions; where the reputed meaning is accurately conveyed the issuing party is given credit for knowing the underlying truth, without burdening the transaction with a test of the truth, a discussion of a text's content.

Like all symbolic currencies, the pace of commerce quickens where the symbol of the good is exchanged prior to the good itself needing to be mobilized. A utility of reputed rather than real meanings is to save scholars from the existential crisis besieging them: the pace of the publication of scholarship has long outpaced anyone's capacity to read it. Reputed meanings allow for the accumulation of a greater body of understanding than would be possible if texts were studied directly. When taken to an extreme this becomes a collective collusion against or stereotype where a fairly thin reputation may stand in for a particular text without anyone ever demanding to see the goods. The deflation of a reputed meaning is to demand that a person wielding it perform an extra feat to demonstrate that they have command of a text's contents. Like any status challenge the target will pay the debt of their knowledge or ignorance with a credit or debit to their own reputation.

Taking another step down the collusion path, professions may violate educational norms by trading in reputed meanings rather than direct readings of texts. This is an encryption of their meaning that works exactly as the password. Only members of a subfield may understand the reputed meaning of a text, who in clerical fashion would deign to humiliate a lay person who studied a text outside of the cloister and claimed to know something about it. Parsons would call the factual reading of a text its intrinsic persuasiveness [-@Parsons1963Concept\:48], a value that is put into forebearance when it is symbolically exchanged. If a reputed meaning is elaborated for the sole purpose of esoteric exclusiveness, and the reputation diverges enough from the truth, the colluders may expect to receive status challenges ask requests to demonstrate knowledge that if they fail will deflate their own reputations. Such a scenario is very likely where professional arenas, which demand high volume trading of texts, intersect with educational arenas, which require closer attention to fewer texts. Textbooks, which contain nothing but reputed meaning, represent a good example of a professional rather than an educational approach to teaching.

***

> NB: *The remainder is unorganized but lays out general concepts relevant to cultural closure and social stratification*

***

## Ubiquity and Esotericism in Culture

Genre is a form of meta-expertise called *ubiquitous discrimination* [@Collins2007Rethinking\:45], which reflects a layperson's ability to make judgments (genre classifications) about what might otherwise be considered esoteric content. Ubiquitous knowledge is assumed to be available to all members of a society, even if not everyone necessarily acquires it. The availability of knowledge is a critical articulation point between cultural systems and social systems.

Bodies of knowledge and practice, cultures, exist because of yet apart from particular people. While some cultures are ubiquitous and inculcated in all members of the societies in which they are substantiated, others are esoteric and marked by significant barriers to learning them. Such esoteric cultures are as inaccessible as they are unnecessary. A child who does not learn what to eat and how to eat it in her local culture will have great difficulty doing anything else in her society. Food culture is of the ubiquitous type and is not difficult to learn. On the other hand, a child who does not master scripture will be ashamed at temple, but shame is bearable in a way that hunger is not. Scripture is of the esoteric type; knowledge of it enables special abilities and grants access to restricted aspects of a society, but ignorance of it does not threaten one's lay livelihood. Even in religiously totalitarian societies, what religious knowledge is necessary will be ubiquitous. What religious knowledge is esoteric can be safely left to the clergy. It is not too narrowly circular to say that the knowledge that informs daily life is the easiest to acquire, and that the mere act of living also reproduces that knowledge within contexts that are themselves ubiquitous. Whether relationships of ubiquity are familial, economic, or state relations varies by society, but no society lacks ubiquitous culture and the means of reproducing it.

Esoteric cultures, then, are removed from ubiquitous ones though they depend on them. They require specialized social relationships for their reproduction in populations. These special relationships may be called fields of cultural production (FCP). FCPs are both reproductive of extant knowledge and productive of novel knowledge relevant usually only to the field itself. To the extent that esoteric cultures are complicated or otherwise have high entropy, the failure to reproduce their cultural content is always an existential threat. While it is a guarantee that cultural content is constantly actually lost to reproduction failures, cultures that nonetheless persist historically must always have a socially structured FCP that, in inculcating new members and reinforcing the knowledge of extant members, resists the entropic decay that would otherwise lead to extinction.

The scope of a culture has a knowledge and a social dimension. Units of knowledge are both discrete and combinatoric. Discretely, the size of a culture can be measured by a count of co-occurring ideas and skills. The utility of knowledge, for instance as instantiated in an FCP, often depends on the combination and interaction of such discrete elements. The mass of knowledge in a culture is related to the count of units and to the ease with which those units can be learned, thought, or deployed in meaningful activity. Some cultures are easier than others, and it is the effort-adjusted size that is the real mass of the ideational content of a culture.

Not all sociologically relevant information is cultural. In the triadic relationship among culture, social structure, and personality, psychological concepts like schema that are sometimes treated as constitutive of social structure [@Sewell1992Theory] do not belong in the category of culture. Schemas allow personalities to organize their responses to a world that includes many things beside culture. In order for cultures and social structures to function stably in time, they depend on the successful operation of schemas, but they do not necessarily provision them. An only partial exception is the limiting and very specialized cases of pedagogical institutions. A culture can only exist if people can reproduce it, but the people must solve the psychological problems of cognition on their own. Whereas culture is fungible in its different mediated forms, there is no reason to believe that a "single schema" occurs across a population of people. There are no one-size-fits-all solutions to human motivation, and schemas will to a large extent be idiosyncratic, adapted as they must be to the particular circumstances in which people as träger find themselves.

What cultures can do to hedge their bets against the instability of personalities is to introduce kinds of knowledge adapted to cognitive problems. Schutz identifies systems of relevance from the side of personalities, and here we understand the same from the side of cultures.

People know culture and it does not appear apart from them. Put differently, culture is information and people are the media that concretely manifest it. The size of a culture is the count of the unique ideas and idea combinations appearing in a deduplicated media catalog, excluding possible but unrealized combinations. The potential of a culture is the size of the realized and unrealized combinations, where the number of elements in a set is limited by a given historical cognitive and technological memory capacity. The potential of a real culture is always greater than its size, as combination novelty always easily exceeds the available media.

The social mass of the culture is the enumeration of the media in which cultural content actually appears historically. The cultural mass is copied piecemeal among a population of knowers. The mass may be enlarged by information technology by making it easier to access and transmit culture, but the artifacts and technology themselves do not count in the mass of the culture. Real, historical human nervous systems, including language expression,

Dead cultures cannot live again because the dead part, the social part, is highly ephemeral. Even if a culture leaves material and symbolic artifacts, the "dead" parts are precisely those human relationships that would socialize new members in particular ways that cannot be deduced by people who never belonged to begin with, namely the archaeologists of the future. Such archaeologists belong to the FCP of their own time, and approach the historical artifacts of a dead culture as any other FCP approaches regular patterns in the world, as subject to their own particular cultural logics.

Reproduction does not necessarily imply long term consistency of cultural content, indeed a high level of knowledge loss may be a sign of historical stability in an esoteric culture if it results from a highly productive FCP. An oversupply of cultural content increases the chances that some, any culture can be conveyed into the future in a chain of descent.

Esoteric knowledge is essentially cryptic, ubiquitous knowledge essentially evident. Crypticism means that laity cannot acquire knowledge on their own, that is, without socially structured access to an FCP. Esotericism is the social consequence of crypticism. Cultures vary by knowledge features, as knowledge is a social axis of power along which status hierarchy necessarily develops. Knowledge asymmetry structures social relationships, usually leading to status inequality.

High entropy cultures must socialize new and maintain existing members like any culture, but their complications also tend to be generative of novelty.

The ubiquitous cultures will be learned because there is nothing in a society to do without knowing them, while esoteric ones are guaranteed to be forgotten by most, swapped easily for the always ready ubiquitous alternatives. Ubiquitous cultures have high ambient findability [@Morville2009Ambient], they can be transparently acquired for instance through mimicry [@DiMaggio1983Iron].

FCPs are social structures that can be thought of as the articulation points between people and a special type of culture that is associated with higher education.

To be sure, if esoteric cultures are marked by asymmetries of knowledge between laity and clergy, to continue with the religious example, one must admit that such asymmetries exist in ubiquitous culture as well, as in the supposed ignorance of a child against the learning of an adult. The ignorance of children combined with their megalomania is a useful example of how social structures operate. Social structures are always culturally conservative; a child's ignorance is a generative force, as they may attempt to solve problems in novel ways, and their efforts will frequently be corrected by the experts. Whether the correction takes marks the chagrin of the parent. Children quickly become specialists in their own FCPs, but this is never because they aren't also aware of the ubiquity. They may know it, it may bore them, and they efface it for fun. But they know what is ubiquitous; their proximity to ignorance of it may animate their creative abrogation of culture. The essentially conservative function of pedagogy will stamp out that creative flame in time. Indeed children are a great source of entropy for ubiquitous culture, hence the large investment in education generally.

This evolutionary argument can be more simply stated as, complicated cultures cannot exist for very long without stewardship.

## Discipline

To return to disciplines, answering such questions would put the researcher in an adisciplinary predicament, for it would mean eschewing the scope restrictions cherished by disciples. The challenges of a meta-disciplinary analysis are manifold and uncertain. One is as likely to grow her audience as to lose it altogether. She risks the dilettantism of a jack-of-all-trades. What's worse, she exposes herself to a dizzying scale of content to consider. If disciplines are indeed functional, then the meta-analysis that effaces disciplines risks being dysfunctional. The upside, however, is appealing. If the universe of meanings given to the term genre does contain complementary uses, a meta-analysis will allow one to consider the consequences of the now arbitrary segregation of a superior metaconcept across disciplinary boundaries. Both sides of the divide could be strengthened by a cultural exchange of their respective terms. The redundancy of parallel discovery can be avoided.

Pathologies of disciplinarity can be diagnosed and treated. Disciplines are social substructures embedded in a larger society and culture. Disciplinarity is a kind of controlled ignorance exchanged for access to secret knowledge. The wayward uses of a term like genre are always lurking at the edges of the firelight defined by a particular disciplinary camp. Discipline as rigor instructs disciples to resist flirtations with the available complexity of the term. The essential tension is very rarely between what is known and unknown; rather it is more commonly between what is known "here" versus what we are conditioned to be willfully ignorant of "there".

This definition of discipline is isomorphic with that of genre, in that disciplines are another form of categorical decision making, just at a higher level. Disciplines are supergenres that reflect the nesting of categories. In music Lena and Petersen [-@Lena2008Classification\:698] have followed Ennis [-@Ennis1992seventh] in referring to supergenres like rock-n-roll or rhythm and blues "streams", which are genres linked in time by any of a number of contiguities, e.g. sound, scene, artist, or market. What may distinguish disciplines in a more serious way is the institutional underpinning of the category. If genres are formed by the categorical thinking of disciples, disciplines are formed by the categorical thinking of patrons, the powerful actors like university administrators, state legislators, and grant makers who manage the economic foundation of scholarly careers, as well as the elite disciples who interface with these stakeholders. Where genre labels are inscribed onto cultural products, texts, discipline labels are inscribed onto cultural infrastructure like funding lines, buildings, and personnel themselves.

To impose a sociological gloss on the term, these varied uses of genre would make reviewing the literature on the topic difficult, were it not for the discipline structure of the academy. The uses of the term genre are themselves systematically organized by discipline, and a disciple who is adequately trained will know the correct ways to use the term in her local context. To use genre as a disciplinary convention means to first identify your location in the disciplinary field, and then to accept the limitations on scope by excluding those treatments of the term that are extradisciplinary, that is, irrelevant. Disciplinary structure reduces the true cultural complexity of the meaning of genre to a restricted form, which in turn allows humble knowledge workers to engage upon a set of shared assumptions. Such simplicity begets new complexity as disciples spin out the consequences of their local use of genre.

In the sociology of culture, genre is a form of classification enacted by people in various social contexts. In the context of industrial capitalism, genre is an economic principle helping to organize supply and demand within markets for cultural products. There actors see genres among the borders between economic, social, and cultural uses, as a market category helping them acquire or produce content, as a card in proximate games of prestige, or as something to taste, to consume and enjoy directly. Less often genre is knowledge, a component of culture separate from taste, that is a factor in the formation of ideas and skills, whether these lead in turn to economic production or not.

Genre's meaning is context specific and variable across sociological subfields, though it is amplified in empiricist fashion by economy and society approaches that reduce genre to the act of classification itself. I say empiricist because of the empirical ease with which the classification or labeling actions are observed. Especially with Internet distribution systems, it becomes trivial for corporations to observe when a consumer labels her preferences while browsing a content catalog; it is much harder to observe the ideas that consuming a particular piece of content sparks in the mind.

In cultural studies genre is used much differently and much more in accordance with its etymology. To the humanist, genre is an ontological phenomenon, which is to say, genres are differentiated from each other by combinations of discrete features of signs and signifieds. Humanists are trained to establish these ontologies through methodological readings of texts and through cultivation of theories of genre types. These methods are at the same time empirical and interpretive, because in consuming objective texts the researcher actually observes the ideas that form in her own consciousness, and they may hope that others have a resonant experience. Genres have more substance to them for humanists than they do for sociologists. For sociologists of culture, genres are how people use genre labels, while for humanists, genres are knowledge.

As I have said, the meaning of genre for a sociologist of culture is economistic, at the same time a market category and a taste configuration for consumers. The term differs for a sociologist of knowledge, and perhaps for a cultural sociologist. It is ontology as it is for the humanist, however it is not the ontology as represented to the researcher in the consumption of texts. It is the hopelessly unobservable distribution of ontologies appearing in a population of consumers attending to similar texts. The sociologist of knowledge accuses the sociologist of culture of reducing internalist concepts, thought and experience, to externalist ones, taste and preference. The sociologist of culture rejoins, show me proof, and on and on the interlocutors spin around the axis defining the boundary between their subfields.

But this description of subdisciplinary differences really is just an example of a structural theory of genre that is within scope for the sociologist of knowledge and beyond it for the sociologist of culture, due to their epistemological differences. If genres are ontological, then they deeply structure a person's experience of reality. Ontologies form basic perceptual categories, and people with different ontologies of an object experience different things even if oriented to the same objective phenomenon. A ontological theory of genre would, for example, attempt to explain differences in taste as differences in phenomenological perception, whereas a taste theory of genre treats consumption behavior as revealing preferences whose downstream consequences are then explored.

Yet for all the differing treatments of genre mentioned above, do these views really contradict, or are they in fact complementary? Does genre as distribution serve the economic sociologist's goals, or does a lack of ontological substance lead her astray? Does genre as knowledge remain hopelessly unverifiable, or are theoretical constructs necessary to achieve a correct interpretation of facts? Is everyone at the club listening to the same song hearing the same thing?

## History

A final strategy for choosing what to read is a genealogical approach [@Foucault2002order]
