version: 2
jobs:
  build:
    docker:
      - image: brooksambrose/studio:bench
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: build
          command: bash _build.sh
      - run:
          name: deploy
          command: bash _deploy.sh
