version: 2
jobs:
  build:
    docker:
      - image: brooksambrose/portfolio:prod
    steps:
      - checkout
      - run:
          name: pull
          command: git clone https://github.com/brooksambrose/portfolio && cd portfolio
      - run:
          name: build
          command: bash _build.sh
      - run:
          name: deploy
          command: bash _deploy.sh
