version: 2
jobs:
  build:
    docker:
      - image: brooksambrose/studio:bench
    steps:
      - checkout
      - run:
          name: pull
          command: git clone ${PORTFOLIO} && cd $(echo ${PORTFOLIO} | sed -r 's:.+/::')
      - run:
          name: build
          command: bash _build.sh
      - run:
          name: deploy
          command: bash _deploy.sh
      - run:
          name: push
          command: git push origin master
